/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.UnoImplementacion;
/**
 *
 * @author Christian Rodriguez
 * 
 */
public class InicioSesion extends javax.swing.JFrame {
    
    UnoImplementacion inicio;
    ArrayList <String> nickname;
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        inicio = new UnoImplementacion();
        nickname= new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NjugadoresLbl = new javax.swing.JLabel();
        numeroJugadores = new javax.swing.JComboBox<>();
        UsuariosLbl = new javax.swing.JLabel();
        jugador1Txt = new javax.swing.JTextField();
        jugador1Lbl = new javax.swing.JLabel();
        jugador2Txt = new javax.swing.JTextField();
        jugador2Lbl = new javax.swing.JLabel();
        jugador3Txt = new javax.swing.JTextField();
        jugador3Lbl = new javax.swing.JLabel();
        jugador4Txt = new javax.swing.JTextField();
        jugador4Lbl = new javax.swing.JLabel();
        botonJugar = new javax.swing.JButton();
        LogoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        NjugadoresLbl.setText("N° jugadores");

        numeroJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        numeroJugadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                numeroJugadoresItemStateChanged(evt);
            }
        });

        UsuariosLbl.setText("Usuarios");

        jugador1Lbl.setText("J1");

        jugador2Lbl.setText("J2");

        jugador3Txt.setEnabled(false);

        jugador3Lbl.setText("J3");

        jugador4Txt.setEnabled(false);

        jugador4Lbl.setText("J4");

        botonJugar.setText("JUGAR");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartas/icono.png"))); // NOI18N
        LogoLbl.setPreferredSize(new java.awt.Dimension(71, 114));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuariosLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador2Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jugador2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador1Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jugador1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador3Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jugador3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugador4Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jugador4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NjugadoresLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botonJugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NjugadoresLbl)
                            .addComponent(numeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(UsuariosLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugador1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador1Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugador2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador2Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador3Lbl)
                            .addComponent(jugador3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugador4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador4Lbl))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonJugar)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ComboBox para el numero de jugadores
    private void numeroJugadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_numeroJugadoresItemStateChanged
        
        if(numeroJugadores.getSelectedItem()=="2")
        {
            jugador1Txt.setEnabled(true);
            jugador2Txt.setEnabled(true);
            jugador3Txt.setEnabled(false);
            jugador4Txt.setEnabled(false);
        } 
        else if(numeroJugadores.getSelectedItem()=="3")
        {
            jugador1Txt.setEnabled(true);
            jugador2Txt.setEnabled(true);
            jugador3Txt.setEnabled(true);
            jugador4Txt.setEnabled(false);
        }
        else if(numeroJugadores.getSelectedItem()=="4")
        {
            jugador1Txt.setEnabled(true);
            jugador2Txt.setEnabled(true);
            jugador3Txt.setEnabled(true);
            jugador4Txt.setEnabled(true);
        }
    }//GEN-LAST:event_numeroJugadoresItemStateChanged

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        UnoInterfazGrafica abrir = new UnoInterfazGrafica();
        
        
        if(numeroJugadores.getSelectedItem()=="2")
        { 
            if(jugador1Txt.getText().equals("") || jugador2Txt.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Ingrese los nombres de los jugadores seleccionados"); 
            }
            else
            {   
                nickname.add(jugador1Txt.getText());
                nickname.add(jugador2Txt.getText());
                if(inicio.iniciarSesion(nickname))
                {
                    abrir.implementacion = inicio;
                    abrir.setVisible(true);
                    this.setVisible(false);                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Los nombres de usuario no pueden ser repetidos");
                    nickname.clear();
                }
            }
        } 
        else if(numeroJugadores.getSelectedItem()=="3")
        {
            if(jugador1Txt.getText().equals("") || jugador2Txt.getText().equals("")|| jugador3Txt.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Ingrese los nombres de los jugadores seleccionados");
            }
            else
            {
                nickname.add(jugador1Txt.getText());
                nickname.add(jugador2Txt.getText());
                nickname.add(jugador3Txt.getText());
                if(inicio.iniciarSesion(nickname))
                {
                    abrir.implementacion = inicio;
                    abrir.setVisible(true);
                    this.setVisible(false);                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Los nombres de usuario no pueden ser repetidos");
                    nickname.clear();
                }
            }
        }
        else if(numeroJugadores.getSelectedItem()=="4")
        {
           if(jugador1Txt.getText().equals("") || jugador2Txt.getText().equals("") || jugador3Txt.getText().equals("") || jugador4Txt.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Ingrese los nombres de los jugadores seleccionados");
            }
           else
           {
                nickname.add(jugador1Txt.getText());
                nickname.add(jugador2Txt.getText());
                nickname.add(jugador3Txt.getText());
                nickname.add(jugador4Txt.getText());
                if(inicio.iniciarSesion(nickname))
                {
                    abrir.implementacion = inicio;
                    abrir.setVisible(true);
                    this.setVisible(false);                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Los nombres de usuario no pueden ser repetidos");
                    nickname.clear();
                }

           }
        }
    }//GEN-LAST:event_botonJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JLabel NjugadoresLbl;
    private javax.swing.JLabel UsuariosLbl;
    private javax.swing.JButton botonJugar;
    private javax.swing.JLabel jugador1Lbl;
    public static javax.swing.JTextField jugador1Txt;
    private javax.swing.JLabel jugador2Lbl;
    public static javax.swing.JTextField jugador2Txt;
    private javax.swing.JLabel jugador3Lbl;
    private javax.swing.JTextField jugador3Txt;
    private javax.swing.JLabel jugador4Lbl;
    private javax.swing.JTextField jugador4Txt;
    private javax.swing.JComboBox<String> numeroJugadores;
    // End of variables declaration//GEN-END:variables
}
